### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by vvzen** [ced-dev/gstreamer#3]
_node 6.2.0 npm 3.8.9 macOS 10.11.2_

I installed the package in my project, while trying the example code throws this error:

```
events.js:160
      throw er; // Unhandled 'error' event

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at Server._listen2 (net.js:1240:19)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at gstreamer.start (/my/project/path/node_modules/gstreamer/index.js:64:17)
    at Object.<anonymous> (/my/project/path/main.js:3:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)```

**Comment by ced-dev** [comment]
It seems that you already have something listening to port 80, (your web server for instance? :) try another port

**Comment by vvzen** [comment]
Port 80 cannot be accessed, I think, so I tried with port 3000, and I got this error:

`ERROR: pipeline could not be constructed: no element "rtspsrc".`

After connecting to the server, nothing seems to happen.
_Stdout_ says: 
```
Index loaded
Client connected
```
 I used the example code.

I am on macOs and installed gstreamer with brew, could you give me some more explanation on how to use this module?

Thanks
